baseURL:
languageCode: en-us
title: Madan Bazgai
theme: PaperMod
paginate: 5

enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: jDp5imGZh3KQWDa2O3vpUK4o-mDO6hSuCXTa8ALjXYM

minify:
  disableXML: false
  minifyOutput: true

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: Blog
      name: Blog
      url: /blog/
      weight: 5
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 15
    - identifier: projects
      name: Projects
      url: https://github.com/madanbazgai/
      weight: 2
    # - identifier: photoshop
    #   name: Photoshop
    #   url: /photoshop
    #   weight: 0

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "This is a portfolio and blog site created, designed & developed by Madan Bazgai"
  keywords: [Blog, Portfolio, Madan Bazgai, Madan Bajgai, MadMax]
  author: Author - Madan Bazgai
  images: ["<link or path of image for opengraph, twitter-cards>"]
  cover:
    hidden: false
    linkFullImages: true
  # defaultTheme: dark
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  comments: true
  profileMode:
    enabled: true
    title: Madan Bazgai # optional default will be site title
    subtitle: üíªSoftware Engineer | üë®‚ÄçüíªDeveloper
    imageUrl: madmax.avif
    imageTitle: profile picture
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Blog
        url: "/blog/"
      - name: Github
        url: "https://github.com/madanbazgai"
      # - name: Resume
      #   url: ""

  socialIcons: # optional
    - name: email
      url: "mailto:madanbajgai@gmail.com"
    - name: phone
      url: tel:977-980-451-6288
    - name: whatsapp
      url: "https://wa.me/9779804516288"
    - name: twitter
      url: "twitter.com"
    - name: instagram
      url: "https://www.instagram.com/madanbazgai/"
    - name: facebook
      url: "https://www.facebook.com/madanbazgai3"
    # - name: medium
    #   url: "madanbajgai@gmail.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/madanbazgai/"
    # - name: dev
    #   url: ""
    # - name: youtube
    #   url: ""

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text

  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon.ico"
    favicon32x32: "favicon.ico"
    apple_touch_icon: "icons/icon-192x192.png"
    safari_pinned_tab: "icons/icon-192x192.png"

  label:
    text: "Madan Bazgai"
    # icon: icons/icon-192x192.png
    # iconHeight: 35

  analytics:
    google:
      SiteVerificationTag: "jDp5imGZh3KQWDa2O3vpUK4o-mDO6hSuCXTa8ALjXYM"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"
